# Generated by Django 4.2 on 2023-05-05 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
